services:
  postgres:
    image: postgres:17-alpine
    container_name: pg_dev
    env_file:
      - ".env.template"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

    volumes:
      - "pgdata:/var/lib/postgresql/data"

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: hw-15
    env_file:
      - ".env.template"
    ports:
      - "3000:3000"
    volumes:
      - ".:/app"
      - "/app/node_modules"
    depends_on:
      - postgres

volumes:
  pgdata: