services:
  postgress:
    image: postgres:17-alpine
    container_name: pg_dev
    env_file:
      - .env.template
    # expose: [ '5432' ]
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: postgres
      # for init .sh  scripts:
      APP_DB: ${DB_DB}
      APP_USER: ${DB_USER}
      APP_PASSWORD: ${DB_PASSWORD}
    volumes:
      - "pgdata:/var/lib/postgresql/data"
      - "./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
    networks:
      db:
        aliases:
          - db


volumes:
  pgdata:

networks:
  db:
    driver: bridge