networks:
  db:
    driver: bridge

services:
  postgres:
    image: postgres
    container_name: pg_dev
    expose: ['5432']
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - "pgdata:/var/lib/postgresql/data"
    networks:
      db:
        aliases:
          - db

  demo_dev:
    container_name: demo_dev
    depends_on:
      - postgres
    build:
      context: .
      target: dev
    environment:
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - db
    volumes:
      - .:/app
      - /app/node_modules

  demo:
    container_name: demo
    depends_on:
      - postgres
    build:
      context: .
    environment:
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - db

volumes:
  pgdata: