name: 'CI Pipeline'

on:
  pull_request:
    branches:
      - 'develop'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: 'Run reusable build-push action'
        uses: ./.github/actions/build-push
        with:
          node-version: '20'
          directory: 'hw-15'